### PR TITLE
Bug 1666608 - Check for schema incompatibilities before pushing

### LINKED ISSUE #74: Consider failing on invalid schema change
@whd this is basically a question for you. Would you like us to have the schema-generator fail on invalid schema changes, or continue having the current pipeline move to deploy and fail later?

### PR DESCRIPTION
**Pull request by acmiyaguchi**
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1666608)

This also fixes #74.

This adds an extra validation step before pushing schemas to `generated-schemas`. The basis of this is to generate a compact set of columns on the generated BigQuery schemas to determine if any columns are removed. This also refactors the main script for reusable components while developing this.

My testing workflow so far is something like this:

```bash
docker-compose run -v $PWD:/app/mozilla-schema-generator --entrypoint /bin/bash app
source mozilla-schema-generator/bin/schema_generator.sh
# -e causes the container to exit immediately
set +e
setup_git
setup_mps
mozilla-schema-generator/bin/test_validate master
mozilla-schema-generator/bin/test_validate master~5
```

The `test_validate` runs the following command with some output:

<details>
<summary>Click to expand</summary>

```diff
items removed from the base
-telemetry.android-anr-report.9.txt
-telemetry.android-anr-report.6.txt
-telemetry.android-anr-report.4.txt
-telemetry.android-anr-report.3.txt
-telemetry.android-anr-report.10.txt
-telemetry.android-anr-report.2.txt
-telemetry.android-anr-report.5.txt
-telemetry.android-anr-report.1.txt
-telemetry.android-anr-report.7.txt
-telemetry.android-anr-report.8.txt

items added to the base
+activity-stream.on-save-recs.1.txt
+pioneer-core.probes.1.txt
+pioneer-debug.pioneer-enrollment.1.txt
+pioneer-core.deletion-request.1.txt
+pioneer-core.pioneer-enrollment.1.txt
+pioneer-core.survey.1.txt
+pioneer-meta.pioneer-enrollment.1.txt

--- /app/validate_schema_evolution/6be65fba320440a7c479d38e3df66931a639be56_base-revision/firefox-launcher-process.launcher-process-failure.1.txt
+++ /app/validate_schema_evolution/998a2ea5e691ff2cb33d8c604c1e22e341f60386_test-generated-schemas/firefox-launcher-process.launcher-process-failure.1.txt
@@ -8,2 +8,3 @@
root.is_admin_without_uac BOOL
+root.launcher_error.detour_orig_bytes STRING
root.launcher_error.hresult INT64

--- /app/validate_schema_evolution/6be65fba320440a7c479d38e3df66931a639be56_base-revision/firefox-accounts.account-ecosystem.1.txt
+++ /app/validate_schema_evolution/998a2ea5e691ff2cb33d8c604c1e22e341f60386_test-generated-schemas/firefox-accounts.account-ecosystem.1.txt
@@ -1,2 +1,3 @@
root.additional_properties STRING
+root.country STRING
root.document_id STRING
@@ -4,2 +5,3 @@
root.ecosystem_user_id STRING
+root.event STRING
root.metadata.geo.city STRING
@@ -25,3 +27,5 @@
root.normalized_os_version STRING
+root.oauth_client_id STRING
root.previous_ecosystem_user_ids.[] STRING
+root.region STRING
root.sample_id INT64

found incompatible changes
```
</details>

Running the following command generates the following logs:

```
mozilla-schema-generator/bin/test_validate master generated-schemas generated-schemas~5
```

<details>
<summary>Click to expand</summary>

```diff
--- /app/validate_schema_evolution/55863c2f2c9428bf2a5d29f4c5090daac9e75484_base-revision/telemetry.main.4.txt
+++ /app/validate_schema_evolution/485be1e70334be6b858b522c354f3487a9c05b3d_generated-schemas/telemetry.main.4.txt
@@ -970,3 +970,8 @@
root.payload.histograms.http2_fail_before_settings STRING
+root.payload.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.histograms.http3_request_per_conn STRING
+root.payload.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.histograms.http3_timer_delayed STRING
+root.payload.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.histograms.http_09_info STRING
@@ -3396,2 +3401,6 @@
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -4378,2 +4387,4 @@
root.payload.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -5270,3 +5281,8 @@
root.payload.processes.content.histograms.htmleditors_with_resizers STRING
+root.payload.processes.content.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.processes.content.histograms.http3_request_per_conn STRING
+root.payload.processes.content.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.processes.content.histograms.http3_timer_delayed STRING
+root.payload.processes.content.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.processes.content.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.processes.content.histograms.http_09_info STRING
@@ -7642,2 +7658,6 @@
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -8571,2 +8591,4 @@
root.payload.processes.content.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.processes.content.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -8739,2 +8761,4 @@
root.payload.processes.content.keyed_scalars.pictureinpicture_opened_method.[].value INT64
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].key STRING
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].value INT64
root.payload.processes.content.keyed_scalars.telemetry_accumulate_unknown_histogram_keys.[].key STRING
@@ -9184,2 +9208,6 @@
root.payload.processes.parent.keyed_scalars.update_bitshresult.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_keywordoffer.[].key STRING
@@ -9192,2 +9220,6 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_shortcut.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_newtab.[].key STRING
@@ -9196,2 +9228,4 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_urlbar.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_typed.[].key STRING
@@ -9401,2 +9435,3 @@
root.payload.processes.parent.scalars.media_blocked_no_metadata_endup_no_audio_track INT64
+root.payload.processes.parent.scalars.media_element_in_page_count INT64
root.payload.processes.parent.scalars.media_page_count INT64

--- /app/validate_schema_evolution/55863c2f2c9428bf2a5d29f4c5090daac9e75484_base-revision/telemetry.saved-session.4.txt
+++ /app/validate_schema_evolution/485be1e70334be6b858b522c354f3487a9c05b3d_generated-schemas/telemetry.saved-session.4.txt
@@ -970,3 +970,8 @@
root.payload.histograms.http2_fail_before_settings STRING
+root.payload.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.histograms.http3_request_per_conn STRING
+root.payload.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.histograms.http3_timer_delayed STRING
+root.payload.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.histograms.http_09_info STRING
@@ -3396,2 +3401,6 @@
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -4378,2 +4387,4 @@
root.payload.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -5270,3 +5281,8 @@
root.payload.processes.content.histograms.htmleditors_with_resizers STRING
+root.payload.processes.content.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.processes.content.histograms.http3_request_per_conn STRING
+root.payload.processes.content.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.processes.content.histograms.http3_timer_delayed STRING
+root.payload.processes.content.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.processes.content.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.processes.content.histograms.http_09_info STRING
@@ -7642,2 +7658,6 @@
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -8571,2 +8591,4 @@
root.payload.processes.content.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.processes.content.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -8739,2 +8761,4 @@
root.payload.processes.content.keyed_scalars.pictureinpicture_opened_method.[].value INT64
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].key STRING
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].value INT64
root.payload.processes.content.keyed_scalars.telemetry_accumulate_unknown_histogram_keys.[].key STRING
@@ -9184,2 +9208,6 @@
root.payload.processes.parent.keyed_scalars.update_bitshresult.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_keywordoffer.[].key STRING
@@ -9192,2 +9220,6 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_shortcut.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_newtab.[].key STRING
@@ -9196,2 +9228,4 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_urlbar.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_typed.[].key STRING
@@ -9401,2 +9435,3 @@
root.payload.processes.parent.scalars.media_blocked_no_metadata_endup_no_audio_track INT64
+root.payload.processes.parent.scalars.media_element_in_page_count INT64
root.payload.processes.parent.scalars.media_page_count INT64

--- /app/validate_schema_evolution/55863c2f2c9428bf2a5d29f4c5090daac9e75484_base-revision/firefox-desktop.metrics.1.txt
+++ /app/validate_schema_evolution/485be1e70334be6b858b522c354f3487a9c05b3d_generated-schemas/firefox-desktop.metrics.1.txt
@@ -65,2 +65,4 @@
root.metrics.string.ping_reason STRING
+root.metrics.timespan.fog_initialization.time_unit STRING
+root.metrics.timespan.fog_initialization.value INT64
root.normalized_app_name STRING

--- /app/validate_schema_evolution/55863c2f2c9428bf2a5d29f4c5090daac9e75484_base-revision/telemetry.first-shutdown.4.txt
+++ /app/validate_schema_evolution/485be1e70334be6b858b522c354f3487a9c05b3d_generated-schemas/telemetry.first-shutdown.4.txt
@@ -970,3 +970,8 @@
root.payload.histograms.http2_fail_before_settings STRING
+root.payload.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.histograms.http3_request_per_conn STRING
+root.payload.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.histograms.http3_timer_delayed STRING
+root.payload.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.histograms.http_09_info STRING
@@ -3396,2 +3401,6 @@
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -4378,2 +4387,4 @@
root.payload.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -5270,3 +5281,8 @@
root.payload.processes.content.histograms.htmleditors_with_resizers STRING
+root.payload.processes.content.histograms.http3_blocked_by_stream_limit_per_conn STRING
root.payload.processes.content.histograms.http3_request_per_conn STRING
+root.payload.processes.content.histograms.http3_sending_blocked_by_flow_control_per_trans STRING
+root.payload.processes.content.histograms.http3_timer_delayed STRING
+root.payload.processes.content.histograms.http3_trans_blocked_by_stream_limit_per_conn STRING
+root.payload.processes.content.histograms.http3_trans_sending_blocked_by_flow_control_per_conn STRING
root.payload.processes.content.histograms.http_09_info STRING
@@ -7642,2 +7658,6 @@
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_script_shift_attributes_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptminsize_attribute_page STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_document STRING
+root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_scriptsizemultiplier_attribute_page STRING
root.payload.processes.content.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document STRING
@@ -8571,2 +8591,4 @@
root.payload.processes.content.keyed_histograms.http3_connecttion_close_code.[].value STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].key STRING
+root.payload.processes.content.keyed_histograms.http3_time_to_reuse_idle_connecttion_ms.[].value STRING
root.payload.processes.content.keyed_histograms.http_cache_disposition_3.[].key STRING
@@ -8739,2 +8761,4 @@
root.payload.processes.content.keyed_scalars.pictureinpicture_opened_method.[].value INT64
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].key STRING
+root.payload.processes.content.keyed_scalars.printing_paper_size.[].value INT64
root.payload.processes.content.keyed_scalars.telemetry_accumulate_unknown_histogram_keys.[].key STRING
@@ -9184,2 +9208,6 @@
root.payload.processes.parent.keyed_scalars.update_bitshresult.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_bookmarkmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_handoff.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_keywordoffer.[].key STRING
@@ -9192,2 +9220,6 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_shortcut.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabmenu.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_tabtosearch.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_newtab.[].key STRING
@@ -9196,2 +9228,4 @@
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_topsites_urlbar.[].value INT64
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].key STRING
+root.payload.processes.parent.keyed_scalars.urlbar_searchmode_touchbar.[].value INT64
root.payload.processes.parent.keyed_scalars.urlbar_searchmode_typed.[].key STRING
@@ -9401,2 +9435,3 @@
root.payload.processes.parent.scalars.media_blocked_no_metadata_endup_no_audio_track INT64
+root.payload.processes.parent.scalars.media_element_in_page_count INT64
root.payload.processes.parent.scalars.media_page_count INT64

no incompatible changes detected
```
</details>

This generates the following folder in the app route with the corresponding schemas:

```bash
app@4fa21f97c7c0:~$ ls -l /app/validate_schema_evolution
+ ls --color=auto -l /app/validate_schema_evolution
total 228
drwxr-xr-x 2 app app 36864 Oct  7 00:01 18c22f3dc7a195082ab572db49147674b01f45bc_test-generated-schemas
drwxr-xr-x 2 app app 36864 Oct  6 23:59 89ae26322ae3e44105fe4e6fb65b2f0e243a166f_base-revision
drwxr-xr-x 2 app app 36864 Oct  6 23:58 907d6442ede68ea79032cae0333c2a9f09a38c67_base-revision
drwxr-xr-x 2 app app 36864 Oct  6 23:57 907d6442ede68ea79032cae0333c2a9f09a38c67_test-generated-schemas
drwxr-xr-x 2 app app 36864 Oct  6 23:56 bac79a33459fcc5084d08e2d3170172ec818f22b_base-revision
drwxr-xr-x 2 app app 36864 Oct  6 23:59 cc5f6746a9385d5d5c03f09575b636a80e557eea_test-generated-schemas
```

This generates a flat folder with BigQuery schemas in them. It should be possible to apply schemas between two revisions to an dataset too.

### CODE REVIEW

File: bin/generate_commit [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+        exit 1
+    fi
+    git checkout "$mps_branch_source"
+    # delete the working branch and no-op if it doesn't exist
+    git branch -D "$mps_branch_working" || :
+    git checkout -b "$mps_branch_working"
+    generate_schemas "$mps_root" "$mps_branch_source"
+    commit_schemas "$mps_root" "$mps_branch_source" "$mps_branch_publish"
+    popd
+}
```
Comment (fbertsch) [inline bin/generate_commit:169]:
```suggestion
}

```

File: bin/schema_generator.sh [hunk 2]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
+        "$MPS_BRANCH_SOURCE" \
+        "$MPS_BRANCH_PUBLISH"
+
+    cd mozilla-pipeline-schemas
     git push || git push --set-upstream origin "$MPS_BRANCH_PUBLISH"
+    popd
 }
 
-main "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
```
Comment (fbertsch) [inline bin/schema_generator.sh:121]: This is a big improvement for testing, good call. It was always annoying that I had to copy+paste the functions into the container

File: bin/schema_generator.sh [hunk 3]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
-    # Copy aliased BQ schemas into place
-    alias_schemas $ALIASES_PATH .
-
-    # Push to branch of MPS
-    cd ../
-    commit_schemas
+    pushd .
+    # the base directory in the docker container
+    cd /app
+    if ! stat "$HOME/.ssh/id_ed25519"; then
```
Comment (fbertsch) [inline bin/schema_generator.sh:106]: What is this conditional checking for? Would be good to document it.

File: bin/schema_generator.sh [hunk 4]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
-    # Keep only allowed schemas
-    filter_schemas
-
-    # Copy aliased BQ schemas into place
-    alias_schemas $ALIASES_PATH .
-
-    # Push to branch of MPS
-    cd ../
-    commit_schemas
+    pushd .
```
Comment (fbertsch) [inline bin/schema_generator.sh:103]: 💯

File: bin/schema_generator.sh (hunk 3 above)
Comment (fbertsch) [reply bin/schema_generator.sh:106]: Looks like this is preventing us from setting up git again on re-runs in the same container, is that right? I'm a little concerned about making local dryruns behave differently when re-running.

File: bin/schema_generator.sh [hunk 5]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
+    local mps_branch_temp="base-revision"
+    # shellcheck disable=SC1090
+    source "${BIN}/generate_commit"
+
+    # We copy the base branch into a new temporary head, since it could point to
+    # the publish branch. Because the publish branch is the branch with the new
+    # commits, we can't simply reuse the branch head since it will move.
+    pushd .
+    cd "$mps_root"
+    git checkout "$mps_branch_publish"
```
Comment (fbertsch) [inline bin/schema_generator.sh:88]: The many faces of `git checkout` are readily apparent here

File: bin/test_validate [hunk 6]
```diff
@@ -0,0 +1,21 @@
+#!/usr/bin/env bash
+
+set -x
+
+BIN="$(realpath ${BASH_SOURCE%/*})"
+# shellcheck disable=SC1090
+source "${BIN}/schema_generator.sh"
+
+MPS_ROOT=/app/mozilla-pipeline-schemas
+# source for the schemas, for testing use something like master~5
```
Comment (fbertsch) [inline bin/test_validate:10]: Would be nice to document these at the top of the file

File: bin/schema_generator.sh [hunk 7]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
-    git checkout $MPS_BRANCH_WORKING -- schemas
-    git commit --all \
-        --message "Auto-push from schema generation [ci skip]" \
-        --message "$(create_changelog)" \
-        || echo "Nothing to commit"
+function validate_generate_commit() {
+    local mps_root=$1
+    local mps_branch_source=$2
+    local mps_branch_publish=$3
+    local mps_branch_base=${4:-$mps_branch_publish}
```
Comment (fbertsch) [inline bin/schema_generator.sh:78]: When would we use this function with `mps_branch_base` different from `mps_branch_publish`?

File: bin/schema_generator.sh [hunk 8]
```diff
@@ -56,124 +52,72 @@ function setup_git_ssh() {
...
-    git checkout "$MPS_BRANCH_PUBLISH" || git checkout -b "$MPS_BRANCH_PUBLISH"
-
-    # Keep only the schemas dir
-    find . -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
-    git checkout $MPS_BRANCH_WORKING -- schemas
-    git commit --all \
-        --message "Auto-push from schema generation [ci skip]" \
-        --message "$(create_changelog)" \
-        || echo "Nothing to commit"
+function validate_generate_commit() {
```
Comment (fbertsch) [inline bin/schema_generator.sh:74]:
```suggestion
function validate_and_generate_commit() {
```

This seems a bit clearer in describing what this procedure is doing

File: bin/validate_bigquery [hunk 9]
```diff
@@ -0,0 +1,167 @@
...
+import json
+import difflib
+import sys
+
+BASE_DIR = Path("/app").resolve()
+
+
+@click.group()
+def validate():
+    pass
```
Comment (fbertsch) [inline bin/validate_bigquery:15]: Was this be design? The default behavior of this script is to do nothing?

File: bin/validate_bigquery [hunk 10]
```diff
@@ -0,0 +1,167 @@
...
+    "--repository",
+    type=click.Path(exists=True, file_okay=False),
+    default=BASE_DIR / "mozilla-pipeline-schemas",
+)
+@click.option(
+    "--artifact",
+    type=click.Path(file_okay=False),
+    default=BASE_DIR / "validate_schema_evolution",
+)
+def local(head, base, repository, artifact):
```
Comment (fbertsch) [inline bin/validate_bigquery:108]: Should this be the validate function?

File: bin/validate_bigquery [hunk 11]
```diff
@@ -0,0 +1,167 @@
...
+                    n=1,
+                )
+            ]
+        )
+        if not diff:
+            # no difference detected
+            continue
+        # check if this is an error condition
+        print(diff + "\n")
+        status |= check_evolution(base_data, head_data)
```
Comment (fbertsch) [inline bin/validate_bigquery:156]: s/status/is_failed (or similar)

File: bin/validate_bigquery [hunk 12]
```diff
@@ -0,0 +1,167 @@
...
+    "--repository",
+    type=click.Path(exists=True, file_okay=False),
+    default=BASE_DIR / "mozilla-pipeline-schemas",
+)
+@click.option(
+    "--artifact",
+    type=click.Path(file_okay=False),
+    default=BASE_DIR / "validate_schema_evolution",
+)
+def copy(head, repository, artifact):
```
Comment (fbertsch) [inline bin/validate_bigquery:46]: We could drop this function entirely and use something [like this](https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/scrapers/git_scraper.py#L53) to instead get the files at both commits during `validate`. That would simplify the above bash script and make this a little less reliant on local state.

File: bin/generate_commit [hunk 13]
```diff
@@ -0,0 +1,169 @@
...
+    # the generator is run. However, the heuristic of using the latest commit
+    # date works well enough.
+    start_date=$(git log "${mps_branch_publish}" -1 --format=%cd --date=iso)
+    git log "${mps_branch_source}" \
+        --since="$start_date" \
+        --pretty=format:"%h%x09%cd%x09%s" \
+        --date=iso
+}
+
+function commit_schemas() {
```
Comment (fbertsch) [inline bin/generate_commit:102]: Did anything change when you moved these functions to the new file?

**Review by fbertsch — CHANGES_REQUESTED** [review]
We should have some explicit tests of the schema evolution checks in `validate_bigquery`.

File: bin/validate_bigquery (hunk 9 above)
Comment (acmiyaguchi) [reply bin/validate_bigquery:15]: This is just the group entrypoint for click.

File: bin/validate_bigquery (hunk 10 above)
Comment (acmiyaguchi) [reply bin/validate_bigquery:108]: This naming is to contrast with another function I intended ("remote") which applies the schemas to bigquery, but this might be misnamed a this point in time.

Comment (fbertsch) [reply bin/validate_bigquery:108]: Got it, let me know what you think about making it all comparison of local branches.

File: bin/generate_commit (hunk 13 above)
Comment (acmiyaguchi) [reply bin/generate_commit:102]: The only thing that changed is that these now require path to the schema repository instead of relying on the absolute path within the container. They generated the same schemas.

File: bin/schema_generator.sh (hunk 3 above)
Comment (acmiyaguchi) [reply bin/schema_generator.sh:106]: No, this is preventing setting up ssh again on reruns. I can probably remove this, since calls to `main` are rare in development.

File: bin/schema_generator.sh (hunk 8 above)
Comment (acmiyaguchi) [reply bin/schema_generator.sh:74]: I personally don't like adding in the conjunction, since it makes the function name harder to remember. It's the same reason why I renamed `setup_git_ssh` and `clone_and_configure_mps` to `setup_git` and `setup_mps` respectively. 

It could be interpreted as "validating generated commits" instead of "generate commit and validate the output", though.

Comment (fbertsch) [reply bin/schema_generator.sh:74]: > It could be interpreted as "validating generated commits" instead of "generate commit and validate the output", though.

I agree the conjunction is uglier, but this is why the name seemed confusing.

File: bin/validate_bigquery (hunk 12 above)
Comment (acmiyaguchi) [reply bin/validate_bigquery:46]: I'm not clear how you would check for whether the file was removed or added between commits. I like the idea of local state outside of version control though, since it makes things easier to inspect.

File: mozilla_schema_generator/validate_bigquery.py [hunk 14]
```diff
@@ -0,0 +1,177 @@
...
+    is_error = 0
+
+    # look at the compact schemas
+    head_files = (head_path).glob("*.txt")
+    base_files = (base_path).glob("*.txt")
+
+    a = set([p.name for p in base_files])
+    b = set([p.name for p in head_files])
+
+    is_error |= check_evolution(a, b, verbose=True)
```
Comment (fbertsch) [inline mozilla_schema_generator/validate_bigquery.py:141]:
```suggestion
    # check that we're not removing any schemas
    is_error |= check_evolution(a, b, verbose=True)
```

**Review by fbertsch — APPROVED** [review]
🚢
